# Generated by Django 4.2.5 on 2023-11-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_alter_replycomment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="replycomment",
            name="content",
            field=models.TextField(max_length=250),
        ),
    ]
