# Generated by Django 4.2.5 on 2023-10-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_category_options_alter_category_table'),
        ('blog', '0002_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.category', verbose_name='Article Category'),
            preserve_default=False,
        ),
    ]
