# Generated by Django 4.2.5 on 2023-09-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_created_date_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
