# Generated by Django 4.2.5 on 2023-09-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_teacher_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.video'),
        ),
    ]
