# Generated by Django 4.2.5 on 2023-10-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_category_name_alter_course_price_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Categories',
        ),
    ]
