# Generated by Django 4.2.5 on 2023-10-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ManyToManyField(related_name='video_course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('going', 'Going On'), ('done', 'Done')], default='Going On', max_length=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='course_videos', to='courses.video'),
        ),
    ]
