# Generated by Django 4.2.5 on 2023-10-04 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_video_course_video_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='offer_price',
        ),
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(100)),
        ),
    ]
