# Generated by Django 4.2.5 on 2023-10-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_users'),
        ('courses', '0018_alter_course_price'),
    ]

    operations = [
    ]
