# Generated by Django 4.2.5 on 2023-11-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercart",
            name="courses",
        ),
        migrations.AddField(
            model_name="usercart",
            name="courses",
            field=models.ManyToManyField(blank=True, to="cart.cartcourse"),
        ),
    ]
