# Generated by Django 4.2.5 on 2023-11-30 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_remove_usercart_courses_usercart_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercart",
            name="courses",
        ),
    ]
